# Generated by Django 4.2.29 on 2026-04-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('reminder_type', models.CharField(choices=[('medicine', 'Dori'), ('water', 'Suv'), ('meal', 'Ovqat'), ('walking', 'Piyoda yurish'), ('sugar_check', 'Shakar o‘lchovi'), ('doctor', 'Shifokor ko‘rigi')], max_length=30)),
                ('remind_time', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('completed', 'Bajarilgan')], default='active', max_length=20)),
                ('ai_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
