# Generated by Django 4.2.29 on 2026-04-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Ayol'), ('male', 'Erkak'), ('other', 'Boshqa')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('height_cm', models.PositiveIntegerField(default=170)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('waist_cm', models.PositiveIntegerField(default=90)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('preferred_language', models.CharField(default='uz', max_length=20)),
                ('consent_ai_support', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
