# Generated by Django 4.2.29 on 2026-04-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodQueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_name', models.CharField(max_length=120)),
                ('label', models.CharField(choices=[('recommended', 'Tavsiya etiladi'), ('caution', 'Ehtiyot bilan'), ('avoid', 'Tavsiya etilmaydi')], max_length=20)),
                ('portion_guidance', models.CharField(max_length=255)),
                ('alternatives', models.TextField()),
                ('ai_explanation', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
