# Generated by Django 4.2.29 on 2026-04-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist_cm', models.PositiveIntegerField()),
                ('food_habits', models.CharField(max_length=255)),
                ('physical_activity', models.CharField(max_length=120)),
                ('sleep_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('stress_level', models.CharField(max_length=50)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('blood_sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('family_history', models.BooleanField(default=False)),
                ('smoking_status', models.CharField(max_length=50)),
                ('alcohol_status', models.CharField(max_length=50)),
                ('existing_conditions', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(choices=[('low', 'Past'), ('medium', 'O‘rta'), ('high', 'Yuqori')], max_length=20)),
                ('risk_percentage', models.PositiveIntegerField()),
                ('ai_explanation', models.TextField()),
                ('recommendations', models.TextField()),
                ('next_steps', models.TextField()),
                ('warning_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskFactorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor_name', models.CharField(max_length=120)),
                ('factor_score', models.PositiveIntegerField(default=0)),
                ('factor_reason', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='riskcheck.riskassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
