# Generated by Django 4.2.29 on 2026-04-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugarReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_type', models.CharField(choices=[('fasting', 'Och qoringa'), ('before_meal', 'Ovqatdan oldin'), ('after_meal', 'Ovqatdan keyin'), ('evening', 'Kechqurun')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_unusual', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
